<Project Sdk="Skyline.DataMiner.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>Low_Code_App_Editor</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<DataMinerType>AutomationScript</DataMinerType>
		<GenerateDataMinerPackage>False</GenerateDataMinerPackage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" />
		<PackageReference Include="Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit.Preview" />
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Microsoft.CSharp" />
		<Reference Include="System.IO.Compression" />
		<Reference Include="System.IO.Compression.FileSystem" />
		<Reference Include="System.Xml.Linq" />
		<Reference Include="WebApiLib">
			<HintPath>..\Dlls\WebApiLib.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<SonarQubeSetting Include="sonar.exclusions">
			<Value>Json/TypeConverter.cs</Value>
		</SonarQubeSetting>
	</ItemGroup>
</Project>