<?xml version="1.0" encoding="utf-8"?>
<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup>
		<!--Runtime-->
		<PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageVersion Include="Skyline.DataMiner.Core.AppPackageInstaller" Version="4.0.0" />
		<PackageVersion Include="Skyline.DataMiner.Dev.Automation" Version="10.3.3" />
		<PackageVersion Include="Skyline.DataMiner.Dev.Utils.SDM.Abstractions" Version="1.0.3" />
		<PackageVersion Include="Skyline.DataMiner.Utils.InteractiveAutomationScriptToolkit.Preview" Version="0.0.0" />
		<PackageVersion Include="Skyline.DataMiner.Utils.SecureCoding" Version="2.2.3" />
		<!--Testing-->
		<PackageVersion Include="coverlet.collector" Version="10.0.1" />
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
		<PackageVersion Include="MSTest.TestAdapter" Version="4.2.3" />
		<PackageVersion Include="MSTest.TestFramework" Version="4.2.3" />
		<!--Analyzers-->
		<PackageVersion Include="Skyline.DataMiner.CICD.CSharpAnalysis.Analyzer" Version="2.1.2" />
		<PackageVersion Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" Version="2.2.3" />
		<PackageVersion Include="StyleCop.Analyzers" Version="1.1.118" />
	</ItemGroup>
</Project>