<Project Sdk="Skyline.DataMiner.Sdk">
	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<RootNamespace>Install_1</RootNamespace>
		<SonarQubeExclude>true</SonarQubeExclude>
	</PropertyGroup>

	<PropertyGroup>
		<DataMinerType>AutomationScript</DataMinerType>
		<GenerateDataMinerPackage>False</GenerateDataMinerPackage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Skyline.DataMiner.Core.AppPackageInstaller" />
		<PackageReference Include="Skyline.DataMiner.Dev.Automation" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Skyline.DataMiner.Utils.SecureCoding.Analyzers" >
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>